name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/tinder
            if [ ! -d ".git" ]; then
              git clone https://github.com/t1mowey/Tinder.git .
            else
              git pull
            fi
            source .venv/bin/activate  # если ты используешь виртуальное окружение
            python -m app.db.init_db
            sudo /bin/systemctl restart tinder

